export { default as CustomFooter } from './layout/CustomFooter.vue'
export { default as CustomLayout } from './layout/CustomLayout.vue'
export { default as Tags } from './page/Tags.vue'
export { default as Blog } from './page/Blog.vue'
export { default as Download } from './page/Download.vue'
export { default as Home } from './page/Home.vue'
export { default as Reading } from './page/Reading.vue'
export { default as Support } from './page/Support.vue'
export { default as Breadcrumb } from './common/Breadcrumb.vue'
export { default as PiButton } from './common/Button.vue'
// @ts-ignore
export { default as CommentGiscus } from './common/CommentGiscus.vue'
export { default as Features } from './common/Features.vue'
export { default as FeatureCard } from './common/FeatureCard.vue'
export { default as GradientText } from './common/GradientText.vue'
export { default as NoteViewer } from './common/NoteViewer.vue'
export { default as SvgIcon } from './common/SvgIcon.vue'
export { default as VersionBadge } from './common/VersionBadge.vue'